### PR TITLE
Modify site and created GIT TAG

### PR DESCRIPTION
**Pull request by martha-vynnyk**

### CODE REVIEW

**Comment by martha-vynnyk** [comment]
Task 5

**Comment by andrii-s-shpitser-lpnu-ua** [comment]
Where is TAG?

**Comment by martha-vynnyk** [comment]
Sorry, forgot to push it

**Comment by martha-vynnyk** [comment]
Now it should be there

**Review by andrii-s-shpitser-lpnu-ua — APPROVED** [review]

**Pull request merged**
